### ISSUE TITLE
Improve ReadTheDocs layout

### ISSUE THREAD

**Issue by tdowrick** [UCL/scikit-surgeryvtk#145]
At the moment, documentation for all modules is difficult to navigate, needs improving.

**Comment by tdowrick** [comment]
I've merged some changes that improve the layout of the ReadTheDocs page (it is fiddly to get RTD to build from a branch other than master).

Within the `doc` folder, I have added a subfolder for each of the submodules (`widgets`, `camera`, `models` etc), each containing its own .rst file, which at the moment just has some improved headings and imports all the documentation from the docstrings. It isn't strictly necessary to have a spearate folder/file for each submodule, but I think it helps organisation.

This doesn't have to be the final layout, but I think it is going in the right direction.

@MattClarkson @thompson318 @mianasbat

**Comment by thompson318** [comment]
I think the layout is good. The structure of docs matches the library layout so it's pretty easy to find stuff now.
