### ISSUE TITLE
add support for vtkunstructuredgrid models

### ISSUE THREAD

**Issue by tdowrick** [UCL/scikit-surgeryvtk#163]

**Comment by MattClarkson** [comment]
Hi Tom, can you remind me what this was for? Can you add description up above?

**Comment by tdowrick** [comment]
Someone I used to work with in EIT now works at Imperial, and VTK is used for visualising reconstructions. He wants to write some code that will automate the current manual loading of data into paraview for visualisation, but all the EIT data uses UnstructuredGrids rather than poly data, so just needed to add it as an option.

**Comment by tdowrick** [comment]
Closed by https://github.com/UCL/scikit-surgeryvtk/commit/d07acc25791740c93fc459ceceea496177f4dcac
