### ISSUE TITLE
Refactor VTKLUSSimulator to accept rot matrices for rendering

### ISSUE THREAD

**Issue by NMontanaBrown** [UCL/scikit-surgeryvtk#168]
# Issue Description

Currently, the set pose method for the VTKLUSSimulator accepts Euler angles, which are then converted into a rot matrix for rendering.

It would be useful to be able to directly pass rot matrices into the renderer, to avoid having to convert rot m -> euler angle -> back into rot m if the user is using rot ms.

**Comment by thompson318** [comment]
I can't find the setpose method. I found set_camera_pose inherherited from vtk_overlay_window but that seems to use matrices. Can you point to the setpose method please.

**Comment by mianasbat** [comment]
It is in 
`sksurgeryvtk/widgets/vtk_lus_simulator.py` 
`tests/camera/test_vtk_camera_model.py`

**Comment by thompson318** [comment]
Found it now, thanks. set_pose, not setpose
https://github.com/UCL/scikit-surgeryvtk/blob/master/sksurgeryvtk/widgets/vtk_lus_simulator.py#L92

**Comment by NMontanaBrown** [comment]
I can work on this issue in my fork - any strong feelings about how to refactor? Thinking of just adding a new class method, like set_pose_with_matrices(), which accepts p2c, l2c, angle_of_handle and pokes the actors, effectively duplicating LOCs: [177-187](https://github.com/UCL/scikit-surgeryvtk/blob/3fafbb9e132fcab7a45006738e1c97e9ce576104/sksurgeryvtk/widgets/vtk_lus_simulator.py#L178) and [138 - 148](https://github.com/UCL/scikit-surgeryvtk/blob/3fafbb9e132fcab7a45006738e1c97e9ce576104/sksurgeryvtk/widgets/vtk_lus_simulator.py#L138).

**Comment by thompson318** [comment]
Try and avoid having 2 methods with duplicate code. You could create set_pose_with_matrices, but then refactor the current set_pose method so all it does is convert the the pose parameters to matrices then calls set_pose_with_matrices

**Comment by NMontanaBrown** [comment]
@thompson318 see changes in #169
