### ISSUE TITLE
CI jobs failing (Linux/Mac)

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgeryvtk#54]
In GitLab by @ThomasDowrick on Mar 19, 2019, 08:36

Job [#11546](https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/SNAPPY/scikit-surgeryvtk/-/jobs/11546) failed for f70e8f9bfb1960ea1812d9d2038b0f9c9d81073a:

@MattClarkson - On Linux CI, test_project_facing_points_invalid_as_normals_not_numpy_array in test_projection_utils.py and one of the tests in test_stereo_overlay_widget.py are failing. The trace leads back to functions in surgerycore/validate_matrix.py, but nothing seems to have been changed in there recently, so I'm guessing this may be something to do with having upgraded to Ubuntu 18? Not sure what though.

Also, the [Mac job](https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/SNAPPY/scikit-surgeryvtk/-/jobs/11410) is now failing one of the tests, which looks like it is related to file permissions:

Windows tests pass OK.

CC'ing @MianAhmad 
```
=================================== FAILURES ===================================
_________________ test_invalid_because_directory_not_readable __________________

    def test_invalid_because_directory_not_readable():
    
        if platform.system() == 'Windows' or not platform.system():
            six.print_('Not running test as Windows doesnt do permissions.')
            return
    
        output_name = 'tests/output/'
        if not os.path.exists(output_name):
            os.mkdir(output_name)
        dir_name = 'tests/output/unreadable'
        if not os.path.exists(dir_name):
            os.mkdir(dir_name)
        os.chmod(dir_name, 0o000)
        with pytest.raises(ValueError):
>           VTKSurfaceModelDirectoryLoader(dir_name)
E           Failed: DID NOT RAISE <class 'ValueError'>

tests/models/test_vtk_surface_model_directory_loader.py:42: Failed
```

**Comment by MattClarkson** [comment]
Over 1 year old. Closing as unit tests are passing ok.
