### ISSUE TITLE
Job Failed #11931

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgeryvtk#57]
In GitLab by @ThomasDowrick on Mar 21, 2019, 13:18

Job [#11931](https://weisslab.cs.ucl.ac.uk/WEISS/SoftwareRepositories/SNAPPY/scikit-surgeryvtk/-/jobs/11931) failed for eb748163dd6f121fd5310c35b3dd893de8c10376:

@MianAhmad - Getting a different failure on imac_main now, any ideas?

**Comment by MattClarkson** [comment]
Too far out of date to be of any use. Closing.
