### ISSUE TITLE
remove installer stage in gitlab-ci

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgeryvtk#79]
In GitLab by @MianAhmad on Jul 22, 2019, 12:18

The installer stage doesn't appear to be necessary.

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Jul 22, 2019, 17:49

created merge request !31 to address this issue

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Jul 22, 2019, 17:49

mentioned in merge request !31

**Comment by thompson318** [comment]
In GitLab by @MianAhmad on Jul 22, 2019, 17:49

Declaration of Installer stage removed as it was not defined below in `gitlab-ci.yml`. Here is the example which declare and define the Installer stage [link](https://github.com/mhoeher/opentodolist/blob/master/.gitlab-ci.yml).

**Comment by MattClarkson** [comment]
No longer needed.
