### ISSUE TITLE
Calcualte left to right transform from two extrinsic matrices

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgeryvtk#98]
In GitLab by @ThomasDowrick on Mar 26, 2020, 13:18

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Mar 26, 2020, 13:20

mentioned in commit b743bddf34e66e2f275f7b4ec276d5a68f9e83bb

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Mar 26, 2020, 13:20

mentioned in commit 2337dd2337cb2bc796b022d0581daf6035de2ee3

**Comment by thompson318** [comment]
In GitLab by @ThomasDowrick on Mar 27, 2020, 09:18

mentioned in commit 71b24428c2358f4950ec813ddd129d3585d69588

**Comment by MattClarkson** [comment]
@tdowrick - can this be closed?

**Comment by tdowrick** [comment]
Yes
