### ISSUE TITLE
Add flag to switch intrinsic camera modes.

### ISSUE THREAD

**Issue by thompson318** [UCL/scikit-surgeryvtk#99]
In GitLab by @MattClarkson on Mar 27, 2020, 17:11

Flag to switch:

In VTKOverlayWindow, modify __update_projection_matrix. 

Switch between:

* set_camera_intrinsics, 
* compute_projection_matrix and then set_projection_matrix.

**Comment by MattClarkson** [comment]
Not needed. See #139.
